name: Lint, Test and Build package
on:
    push:
        branches:
            - '*'
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x, 20.x]
        steps:
            - name: Copy repository
              uses: actions/checkout@v3

            - name: Install deps
              run: yarn ci

            - name: Lint code
              run: yarn lint

            - name: Run tests & coverage
              run: yarn test --coverage

            - name: Run build
              run: yarn build
